# Generated by Django 4.2.3 on 2023-07-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='Advertisements',
        ),
    ]
